//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IoCContainerPageObjectPattern.Core {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MicrositesTestData {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MicrositesTestData() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IoCContainerPageObjectPattern.Core.MicrositesTestData", typeof(MicrositesTestData).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WHAT IS A UIT? Investors Guide to UITs Attractive Opportunity in Closed-End Funds COHEN &amp; STEERS UIT PORTFOLIOS Closed-End Fund UITs Preferred UITs Equity UITs HOW TO ORDER UIT&apos;S If you are a retail client please contact your Financial Adviser and inquire about purchasing AAM Unit Investment Trust products. If you are a registered Financial Adviser and would like to sign into AAM&apos;s website please click here. ADVISORS ASSET MANAGEMENT UNIT INVESTMENT TRUST SALES AND SERVICE DESK: (866) 606-7220 AAM partners  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CohenAndSteersBodyText {
            get {
                return ResourceManager.GetString("CohenAndSteersBodyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To return to the Cohen &amp; Steers website click here..
        /// </summary>
        internal static string CohenAndSteersLandingSubHeaderText {
            get {
                return ResourceManager.GetString("CohenAndSteersLandingSubHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard &amp; Poor&apos;s Financial Services LLC (&quot;S&amp;P&quot;). Reproduction of RatingsXpress-Credit Ratings in any form is prohibited except with the prior written permission of S&amp;P. S&amp;P does not guarantee the accuracy, completeness, timeliness or availability of any information, including ratings, and is not responsible for any errors or omissions (negligent or otherwise), regardless of the cause, or for the results obtained from the use of ratings. S&amp;P GIVES NO EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Disclaimer {
            get {
                return ResourceManager.GetString("Disclaimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For Financial Advisor Use Only - Not For Use With the Public - www.aamlive.com.
        /// </summary>
        internal static string DisclaimerFinancialAdvisorUseOnly {
            get {
                return ResourceManager.GetString("DisclaimerFinancialAdvisorUseOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SPONSOR OF THE AAM PRODUCT LINE OF UNIT INVESTMENT TRUSTS Member SIPC - Member FINRA.
        /// </summary>
        internal static string LandingHeaderText {
            get {
                return ResourceManager.GetString("LandingHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This website is intended for use by Financial Advisors of Merrill Lynch. • Call (866) MLSERVICE with Questions.
        /// </summary>
        internal static string MerrillLynchAllPortfoliosSubHeaderText {
            get {
                return ResourceManager.GetString("MerrillLynchAllPortfoliosSubHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HOW TO TICKET
        ///UIT NEW ISSUE ORDERS
        ///
        ///From your WM Workstation: Other Inventory &gt;&gt; Menu (OCP)
        ///Orders are executed daily at market prices (after initial deposit date).
        ///Prior days prices are posted on the UIT homepage.
        ///UIT ROLLOVER ORDERS
        ///
        ///From your WM Workstation: Orders &gt;&gt; Other Products &gt;&gt; UITs - New Orders
        ///Alerts will be sent to FAs with order entry instructions.
        ///HOW TO ORDER MATERIALS
        ///
        ///Contact your Advisors Asset Management, Inc. Wholesaler.
        ///Wholesaler Territory Map.
        ///MERRILL LYNCH UIT TRADING [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MerrillLynchBodyText {
            get {
                return ResourceManager.GetString("MerrillLynchBodyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This website is intended for use by Financial Advisors of Merrill Lynch. • Call (866) MLSERVICE with Questions.
        /// </summary>
        internal static string MerrillLynchLandingSubHeaderText {
            get {
                return ResourceManager.GetString("MerrillLynchLandingSubHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This website is intended for use by Financial Advisors of Morgan Stanley Wealth Management. Sales Charges, Credits, Volume Discounts • Call (800) 869-0690 with Questions.
        /// </summary>
        internal static string MorganStanleyAllPortfoliosSubHeaderText {
            get {
                return ResourceManager.GetString("MorganStanleyAllPortfoliosSubHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HOW TO TICKET
        ///Place ticket on Morgan Stanley Wealth Management Order Entry System using ticketing symbol or CUSIP. NASDAQ tickers cannot be accepted.
        ///In order to access Sales Charges/FA Credit, please access Primary Issue Trust Finder located at: Ideas--Products--Unit Investment Trust--Primary Issue Trust Finder
        ///HOW TO ORDER MATERIALS
        ///Contact your AAM, Inc Wholesaler.
        ///Wholesaler Territory Map.
        ///MORGAN STANLEY WEALTH MANAGEMENT UNIT INVESTMENT TRUST SALES AND SERVICE DESK:
        ///(800) 869-0690
        ///ADVISORS ASSE [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MorganStanleyBodyText {
            get {
                return ResourceManager.GetString("MorganStanleyBodyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This website is intended for use by Financial Advisors of Morgan Stanley Wealth Management. Sales Charges, Credits, Volume Discounts • Call (800) 869-0690 with Questions.
        /// </summary>
        internal static string MorganStanleyLandingSubHeaderText {
            get {
                return ResourceManager.GetString("MorganStanleyLandingSubHeaderText", resourceCulture);
            }
        }
    }
}
